---
abstract: 'The great new Net::Xero!'
author:
  - 'Lenz Gschwendtner, C<< <norbu09 at cpan.org> >>'
  - 'Lenz Gschwendtner <norbu09@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Xero
no_index:
  directory:
    - examples
    - inc
    - share
    - t
requires:
  Crypt::OpenSSL::RSA: 0
  Data::Random: 0
  File::ShareDir: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Mouse: 0
  Net::OAuth: 0
  Template::Alloy: 0
  XML::LibXML::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
